springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8083}

petstore:
  service:
    product:
      url: "${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}"

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

azure:
  cosmodb:
    host: "${COSMODB_URL:null}"
    master-key: "${COSMODB_MASTER_KEY:null}"
    database-name: "Petstoreapp"
    container-name: "Orders"
  messagebus:
    connection-string: "${CONNECTION_STRING_BUS:null}"
    queue-name: "jhonnypetqueue"

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
